# Generated by Django 5.0.1 on 2024-02-28 13:06

import django.db.models.deletion
import storybook.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storybook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField()),
                ('starting_sentence', models.CharField(max_length=250)),
                ('finished_playthrough', models.BooleanField()),
                ('drawing', models.JSONField(default=list)),
                ('signed_the_book', models.BooleanField()),
                ('decision_of_authorship', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to=storybook.models.Image.get_upload_to)),
                ('description', models.TextField()),
                ('storybook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storybook.storybook')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('storybook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='storybook.storybook')),
            ],
        ),
    ]
