# Generated by Django 4.2.7 on 2024-01-25 15:42

from django.db import migrations, models
import django.db.models.deletion
import storybook.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storybook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('iterations', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to=storybook.models.Image.get_upload_to)),
                ('description', models.TextField()),
                ('storybook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storybook.storybook')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('storybook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='storybook.storybook')),
            ],
        ),
    ]
