# Generated by Django 4.2.7 on 2023-12-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storybook',
            name='status',
        ),
    ]
