# Generated by Django 4.2.7 on 2023-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0002_remove_storybook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storybook',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
