# Generated by Django 4.2.7 on 2023-12-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0003_storybook_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='storybook_images/')),
                ('storybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storybook.storybook')),
            ],
        ),
    ]
