# Generated by Django 4.2.7 on 2023-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
