# Generated by Django 4.2.7 on 2023-12-08 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0007_alter_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='storybook',
            new_name='storybook_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
